version: 0.2
phases:
  build:
    commands:
      - echo Test Diego!!!
      - echo Password 1
      - echo $REACT_APP_PASSWORD1
      - echo Password 2
      - echo $REACT_APP_PASSWORD2
      - echo Password 3
      - echo $REACT_APP_PASSWORD3
