version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Test Diego!!!
      - echo Password 1
      - echo $REACT_APP_PASSWORD1
      - echo Password 2
      - echo $REACT_APP_PASSWORD2
      - echo Password 3
      - echo $REACT_APP_PASSWORD3
      - npm install
      - npm run clean
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: build
cache:
  paths:
    - '/root/.npm/**/*'